In [3]:
!nvidia-smi

Mon Oct 19 06:37:34 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

In [39]:
import numpy as np
import pandas as pd
import seaborn as sns
from pylab import rcParams
from tqdm import tqdm
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from matplotlib import rc
import requests
from pandas.plotting import register_matplotlib_converters
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

In [2]:
%matplotlib inline
%config InlineBackend.figure_format='retina'

register_matplotlib_converters()
sns.set(style='whitegrid', palette='muted', font_scale=1.2)

HAPPY_COLORS_PALETTE = ["#01BEFE", "#FFDD00", "#FF7D00", "#FF006D", "#ADFF02", "#8F00FF"]

sns.set_palette(sns.color_palette(HAPPY_COLORS_PALETTE))

rcParams['figure.figsize'] = 12, 8

RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)

In [36]:
!unzip ./archive.zip

Archive:  ./archive.zip
  inflating: covid19_tweets.csv

In [47]:
df = pd.read_csv("covid19_tweets.csv")
df.head(100)

                                        user_name  ... is_retweet
0                                          ᏉᎥ☻լꂅϮ  ...      False
1                                   Tom Basile 🇺🇸  ...      False
2                                 Time4fisticuffs  ...      False
3                                     ethel mertz  ...      False
4                                        DIPR-J&K  ...      False
..                                            ...  ...        ...
95                                          Safiy  ...      False
96                                TNCoronaUpdates  ...      False
97  CraigBrigham MebaneNC #864511320 #GoodTrouble  ...      False
98                                        The GAA  ...      False
99                                    RumpusGuy64  ...      False

[100 rows x 13 columns]

In [48]:
df.columns

Index(['user_name', 'user_location', 'user_description', 'user_created',
       'user_followers', 'user_friends', 'user_favourites', 'user_verified',
       'date', 'text', 'hashtags', 'source', 'is_retweet'],
      dtype='object')

In [49]:
df = df.iloc[:, [1, 4, 8, 9]]

In [50]:
df.head()

          user_location  ...                                               text
0            astroworld  ...  If I smelled the scent of hand sanitizers toda...
1          New York, NY  ...  Hey @Yankees @YankeesPR and @MLB - wouldn't it...
2      Pewee Valley, KY  ...  @diane3443 @wdunlap @realDonaldTrump Trump nev...
3  Stuck in the Middle   ...  @brookbanktv The one gift #COVID19 has give me...
4     Jammu and Kashmir  ...  25 July : Media Bulletin on Novel #CoronaVirus...

[5 rows x 4 columns]